name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout 
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and export
      uses: docker/build-push-action@v5
      with:
        file: ./src/Dockerfile
        context: ./src
        tags: petefield/home:latest
        outputs: type=docker,dest=/tmp/proxyimage.tar

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: proxy-image
        path: /tmp/proxyimage.tar

  push:

    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: proxy-image
        path: /tmp

    - name: Load artifact into Docker
      run: |
        docker load --input /tmp/proxyimage.tar
        docker image ls -a          

    - name: Push to DockerHub
      run: |
        docker login -u petefield -p ${{ secrets.DOCKERHUB_TOKEN }}
        docker push proxyimage:latest


