name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      working-directory: ./src
      run: docker build . --file Dockerfile --tag petefield/home:$(date +%s) --output type=docker,dest=/tmp/proxy_image.tar
    - uses: actions/upload-artifact@v4
      name: Upload the Docker image to artifacts
      with:
        name: proxy_image
        path: /tmp/proxy_image.tar

  push:

    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: proxy_image
        path: /tmp
    - name: Display structure of downloaded files
      run: ls -R
    - name: load
      run: |
        docker load --input /tmp/proxy_image.tar
        docker image ls -a          


